import React from "react";
import { Gorditas } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SketchGuess",
  description: "Generated by create next app",
};

const gorditas = Gorditas({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gorditas",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gorditas.variable}`}>{children}</body>
    </html>
  );
}
